from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def index(request):
    return render(request, "services/index.html")
def pembuatanaplikasi(request):    
    SEO1 = ["PEMBUATAN APLIKASI KASIR TOKO RESTORAN SEKOLAH"]
    SEO2 = ["aplikasi untuk kebutuhan pembukuan point of sale kasir penjualan, invoice , inventori, sekolah, booking system dan berbagai kebutuhan pembukuan apps ready disini. "]
    title = ["PEMBUATAN APLIKASI"]
    desc = ["Aplikasi sekolah, aplikasi kasir penjualan toko dan restoran,aplikasi akuntansi, aplikasi online shop, aplikasi bisnis , aplikasi boking tempat reservasi."]
    img = ["https://1.bp.blogspot.com/-udm1kuJJ_YM/YY_akT1oZHI/AAAAAAAAR3c/k8EXsbU3J4oqNYOMDt_EhT8pH0HqwndSACLcBGAsYHQ/s626/aplikasi%2Bbisnis.jpg"]
    cta = ["Yap sebuah aplikasi saat ini sangat dibutuhkan untuk kebutuhan perkembangan technology modern dalam mencatat pembukuan dan bekerja dengan cepat secara real time online, ini akan memudahkan pengguna dalam berbagai kebutuhan untuk mempercepat dan mempersingkat serta menambahkan mobilitas dalam pekerjaan, dengan ini semua pembukuan akan tertata lebih rapi dan monitoring kinerja pun semakin mudah.","Aplikasi toko : adalah sebuah type aplikasi yang banyak digunakan pada usaha retil dan grosir dalam implementasi nya, dengan aplikasi ini kita bisa bekerja untuk mencatat pembelian ke supplier, melakukan penjualan ke pelanggan dan mencetak struk kasir via mesin kasir, mencatat kan inventori stok management, cek laporan detail seperti pendapatan income omset, laporan stok dan berbagai kebutuhan lain nya via aplikasi toko kasir sendiri, dan tentunya beragam applikasi toko tersedia dalam digunakan menunjang usaha mu mulai dari simple apps dengan harga murah hingga aplikasi yang lengkap dalam mendukung kinerja usaha bisnis mu.", "aplikasi restoran : adalah sebuah system yang dibutuhkan untuk membantu mempercepat dan merapikan pembukuan pada usaha kuliner, dengan kemampuan nya dengan pembagian divisi maupun untuk single standalone sangat mudah menggunakan aplikasi restoran online ini untuk penerapan berbagai kebutuhan dalam bekerja, dengan waiters tablet order, kitchen display screen, hingga kebutuhan dalam admin untuk cek laporan laporan detail memungkinkan menggunakan nya secara lengkap dan mobile, tentu berbagai resto app tersedia untuk menunjang bisnis kuliner mu mulai dari simple system dengan harga murah hingga lengkap nya fitur yang disediakan mulai reservasi booking online , online order shop dan lain sebagai nya.", "akuntansi apps: aplikasi akuntansi accounting untuk mencatat pembukuan berdasarkan kebutuhan keuangan agar memudahkan dalam pelaporan pajak menjadi lebih baik dengan mencatat debit dan credit transaksi , dengan fitur ini benar benar membantu tugas accounting dan akuntan dalam bekerja dengan cepat serta dukungan simple system yang mudah dipahami oleh pengguna." , "Aplikasi invoice adalah aplikasi yang digunakan dalam menerbitkan faktur jual maupun faktur pajak penjualan dan tentunya dengan dukungan lengkap informasi pembukuan untuk perusahaan seperti pencatatan tender project dengan status pekerjaan, membuat penawaran , dan menerbitkan faktur penjualan serta banyak lagi lain nya.","Aplikasi sekolah menjadi kebutuhan lengkap bagi dunia edukasi untuk mempercepat berbagai kebutuhan baik itu proses belajar mengajar, mencatat pembukuan keuangan sekolah, dan berbagai lain nya khusus untuk dunia pendidikan."]
    themes = ["ilxs6l5Dhfw","3eqJz3KqY1M","Xp_sHwn15aQ","tNBRSJKN8N0","RZ6Jl6rxerk","cenxi37fj-8","KUsp5Rzk9Nc","1r7ZbBvBmo0","IK77uOvJ-pU","zQIjZPnGthc","cIChy757jns","u_afMzfjLpE"]
    pricing = ["Untuk daftar harga dan layanan aplikasi ini bervariatif tergantung dari paket dan tingkat kesulitan serta fitur yang digunakan , jadi untuk kebutuhan web app kamu silahkan hubungi kami untuk mendapatkan solusi terbaik, tenang saja harga layanan kami ini cukup bersahabat untuk digunakan alias murah meriah."]
    return render(request, "services/pembuatanaplikasi.html",{"SEO1":SEO1,"SEO2":SEO2,"title":title,"img":img,"themes":themes,"desc":desc,"cta":cta,"pricing":pricing})
def pembuatanandroid(request):
    SEO1 = ["PEMBUATAN APLIKASI ANDROID MURAH MERIAH"]
    SEO2 = ["Pembuatan Aplikasi ANdroid Modern terbaru up to date untuk toko shop resstoran company profile sekolah dan lain nya"]
    title = ["APLIKASI ANDROID APP"]
    desc = ["Solusi untuk pembuatan aplikasi android informasi mu."]
    img = ["https://1.bp.blogspot.com/-YbzqygBEcxY/YY_VwwqTieI/AAAAAAAAR3U/z-d69ct02KwLTevk6ztSmUpSnzdr6sDZQCLcBGAsYHQ/s666/pembuatan%2Bandroid%2Bterbaru.png"]
    cta = ["Kini dengan technology yang berkembang cukup pesat memiliki sebuah aplikasi android sendiri dapat membantu memberikan informasi detail yang lengkap kepada pelanggan dan pengguna aplikasi android mu, selain itu kita juga bisa memanfaatkan nya sebagai media promosi marketing digital untuk bisnis , untuk toko bisa dengan langsung di integrasikan ke toko online shop page website, atau untuk restoran dengan fitur pesanan online , untuk barbershop salon spa dengan kebutuhan booked online, dan sekolah maupun company profile untuk memberikan edukasi serta informasi mengenai perusahaan , dan dengan memiliki android aplikasi anda dapat menggunakan nya untuk upload ke google playstore . dengan memiliki apk android di playstore akan mewakili lini bisnis anda pada dunia aplikasi sendiri, dengan integrasi website dan android apk maka lengkap sudah kebutuhan technology untuk menunjang bisnis usaha mu. " , "Berbagai technology kami gunakan dalam penerapan nya, mulai dari penggunaan dengan menggunakan native java lang, kotlin , flutter dart, hingga penggunaan technology modern dengan all in one website aplikasi android dalam satu apps via angular, react , svelte menjadikan kesempuraaan untuk memiliki website dan aplikasi android dalam satu proses build, dan atau ingin menggunakan webview untuk proses fetch website kamu ke dalam sebuah aplikasi android pun tersedia dengan harga layanan yang terjangkau. so pilih tema dibawah ini dan mulai upload aplikasi android APK mu ke playstore sekarang. "]
    themes = ["hvzjFQ7nvoQ" , "UsKbCzS3k4E" ,"v7_Ub0lyvAU" , "1zAHrcDytAc" , "-kht4_wnXho" ,"_9dmDzonKPA" , "3ADJF2yuWC0", "RT7o8Za8Hb4" , "OIO88F0C4Ss", "EtB_3hD9GP4","FnMghNtfap8","itfkpehGPq0"]
    pricing = ["Standard paket dengan biaya hanya Rp.1.000.000 saja dengan fasilitas 5 page plus desain standard APK android" , "Premium paket dengan biaya hanya Rp.1.500.000 saja untuk fasilitas 5 page plus desain premium APK android." ,"+ Upload playstore hanya nambah Rp.350.000" ,"+ Halaman hanya Rp.250.000/page nya." ,"Webview untuk konvert website ke aplikasi android hanya Rp.250.000 saja (tidak termasuk upload playstore)."]
    return render(request, "services/pembuatanandroid.html",{"SEO1":SEO1,"SEO2":SEO2,"title":title,"img":img,"themes":themes,"desc":desc,"cta":cta,"pricing":pricing})
def pembuatanwebsite(request): 
    SEO1 = ["PEMBUATAN WEBSITE MODERN TERBARU MURAH MERIAH"]
    SEO2 = ["Solusi terbaik untuk project pembuatan website modern shop toko, restoran cafe rumah makan, company profile dan sekolah dengan technology modern terbaru "]
    title = ["PEMBUATAN WEBSITE TERBARU"]
    desc = ["Solusi terbaik untuk project pembuatan website modern shop toko, restoran cafe rumah makan, company profile dan sekolah dengan technology modern terbaru ."]
    img = ["https://1.bp.blogspot.com/-YN5d4Sv9P8s/YY_awY9_ojI/AAAAAAAAR3o/ZjImPTro0gEEV0JPJvNqsaU8U8JbGCn-QCLcBGAsYHQ/s519/pembuatan%2Bwebsite.png"]
    cta = ["Maju dan berkembang bersama technology kami dalam kebutuhan pembuatan website modern mu, untuk toko shop, restoran cafe rumah makan, sekolah,company profile, gallery seni, artworker, dan berbagai bidang bisnis lain nya , sempurnakan kebutuhan web development mu bersama kami untuk masa depan yang terbaik, dengan berbagai desain unik menarik tentunya serta kebutuhan dalam content management system lengkap dalam kebutuhan web admin untuk mengelola website " , "dukungan technology semakin memudahkan dalam memilih sesuai kebutuhan mu dan tentunya include dengan aplikasi pembuatan website develope team kami sendiri akan menyempurnakan kebutuhan itu, mulai dari laravel the artisan php, symfony , angular new modern site, atau menggunakan wordpress, modx revolutions, hingga penggunaan statis site super cepat generasi web terbaru dengan jekyll, gatsby, react , svelte dan lain nya untuk mendukung technology situs mu menjadi lebih sempurna.", "Tentunya pada premium paket sendiri nantinya akan disesuaikan dengan kebutuhan dalam bekerja, mulai dari kolaborasi technology demi menghasilkan site yang benar benar kekinian , dan dukungan beberapa framework melengkapi develope project situs mu semakin lengkap, dan saat nya kini mulai gunakan layanan pembuatan website kami untuk hasil terbaik, pilih tema dibawah ini , pilih domain dan web mu sudah online , saat nya revolusi digital dimulai bersama kami."]
    themes = ["sMENkpTFTFU" , "H3B0cCc7TcU" , "06lHpX0Fmfk" , "wuvIR7W34M4" , "kIV2DEjHwKg", "fqmIvmc1O_A" , "FOKuedSKZc4" , "BWpSHiOjIZo" , "KgaCUaVdyYE" , "AI2fLF6bgvE", "mDs8BirlC5o" , "9hIJzVtdfxo","PcmgkuQEJRA" , "lxOpSoThms8" , "vqbeeSLq-Fo"]
    pricing = ["PRICING", "Get axcora cms : BASIC : Rp. 410.000/tahun standard themes + domain my.id + webspace 250MB | STANDARD : Rp. 610.000/tahun standard themes + domain com + webspace 250MB | PREMIUM : Rp. 1.564.800/tahun premium themes + POS apps + domain com + webspace 1.500MB " , "Content Management System : Laravel , Symfony , Modx ,Wordpress : Rp.1.564.800/tahun domain com + web space 500MB ","Whatsapp Shop toko online whatsapp - BASIC : Rp.410.000/tahun domain my.id +250MB Webspace | STANDARD : Rp.610.000/tahun domain com + 500MB web space + QR Code digital", "Roboshop cms toko online shop BASIC Rp.1.086.400/tahun domain my.id + 500MB webspace | STANDARD Rp.1.564.800/tahun domain com + 1.5GB Webspace + APK android","Luxury Webapp Phyton Django ,Golang , Ruby on Rails Desain only Rp.1.564.800/ 5 page desain ", "Modern Site : Gatsby , React , Angular, Svelte , Jekyll : Rp.2.564.800 + 5 halaman page + domain com perpanjangan pertahun Rp.1.086.400 untuk tambah halaman + Rp500.000/Page desain" , "Custom : Untuk kolaborasi technology Start Rp.3.468.600 dengan integrasi website + toko online shop + aplikasi kasir toko restoran sekolah"]
    return render(request, "services/pembuatanwebsite.html",{"SEO1":SEO1,"SEO2":SEO2,"title":title,"img":img,"themes":themes,"desc":desc,"cta":cta,"pricing":pricing})
